theme: minima
title: Jackson's Epic Themeless Blog
author: Jackson Fry
email: jfry1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
  This is the most epic site you will ever visit.

# social links
github_username:  JacksonAFry # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
